### PR TITLE
Return array of targetings instead of only first entry.

### PR DESCRIPTION
**Pull request by hwartig**
This will allow retrieving the targetings in batch.

### CODE REVIEW

**Comment by tsujigiri** [comment]
🍺

(very subliminal messaging😁)

**Comment by hwartig** [comment]
@guigs do we still need this?

**Comment by guigs** [comment]
Probably not, but we can merge it anyway

**Comment by dziemba** [comment]
Closing this, since we apparently don't need it. Also, this is a breaking change and would require a major version bump, as far as I can see. Re-open if we still want it :)

**Pull request closed without merging**
